import type { BuffToggle } from '../types/combat'

export const BUFF_PRESETS: BuffToggle[] = [
  {
    id: 'preset-haste',
    name: 'Haste',
    active: false,
    attackMod: 1,
    damageMod: 0,
    acMod: 1,
    saveMod: { ref: 1 },
    description: '+1 attack, +1 dodge AC, +1 Reflex save, extra attack on full attack',
    color: 'primary',
  },
  {
    id: 'preset-bless',
    name: 'Bless',
    active: false,
    attackMod: 1,
    damageMod: 0,
    acMod: 0,
    description: '+1 morale bonus on attack rolls and saves vs fear',
    color: 'primary',
  },
  {
    id: 'preset-inspire-courage-1',
    name: 'Inspire Courage +1',
    active: false,
    attackMod: 1,
    damageMod: 1,
    acMod: 0,
    description: '+1 competence bonus on attack rolls and weapon damage rolls',
    color: 'secondary',
  },
  {
    id: 'preset-inspire-courage-2',
    name: 'Inspire Courage +2',
    active: false,
    attackMod: 2,
    damageMod: 2,
    acMod: 0,
    description: '+2 competence bonus on attack rolls and weapon damage rolls',
    color: 'secondary',
  },
  {
    id: 'preset-flanking',
    name: 'Flanking',
    active: false,
    attackMod: 2,
    damageMod: 0,
    acMod: 0,
    meleeOnly: true,
    description: '+2 bonus on melee attack rolls when flanking an opponent',
    color: 'secondary',
  },
  {
    id: 'preset-bulls-strength',
    name: "Bull's Strength",
    active: false,
    attackMod: 0,
    damageMod: 0,
    acMod: 0,
    abilityMods: { str: 4 },
    description: '+4 enhancement to Strength (+2 mod to attack, damage, STR skills)',
    color: 'secondary',
  },
  {
    id: 'preset-cats-grace',
    name: "Cat's Grace",
    active: false,
    attackMod: 0,
    damageMod: 0,
    acMod: 0,
    abilityMods: { dex: 4 },
    description: '+4 enhancement to Dexterity (+2 mod to AC, Reflex, ranged attacks, DEX skills)',
    color: 'primary',
  },
  {
    id: 'preset-bears-endurance',
    name: "Bear's Endurance",
    active: false,
    attackMod: 0,
    damageMod: 0,
    acMod: 0,
    abilityMods: { con: 4 },
    description: '+4 enhancement to Constitution (+2 mod to Fortitude saves)',
    color: 'secondary',
  },
  {
    id: 'preset-shield-of-faith',
    name: 'Shield of Faith',
    active: false,
    attackMod: 0,
    damageMod: 0,
    acMod: 2,
    description: '+2 deflection bonus to AC',
    color: 'primary',
  },
  {
    id: 'preset-shield-spell',
    name: 'Shield (Spell)',
    active: false,
    attackMod: 0,
    damageMod: 0,
    acMod: 4,
    description: '+4 shield bonus to AC, blocks magic missiles',
    color: 'primary',
  },
  {
    id: 'preset-barkskin',
    name: 'Barkskin',
    active: false,
    attackMod: 0,
    damageMod: 0,
    acMod: 2,
    description: '+2 natural armor bonus to AC',
    color: 'secondary',
  },
  {
    id: 'preset-rage',
    name: 'Barbarian Rage',
    active: false,
    attackMod: 0,
    damageMod: 0,
    acMod: -2,
    saveMod: { will: 2 },
    abilityMods: { str: 4, con: 4 },
    description: '+4 STR, +4 CON, +2 morale to Will saves, -2 penalty to AC',
    color: 'error',
  },
]
