import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#35343a',
        'on-primary': '#00363d',
        'surface-container-high': '#2a292f',
        'tertiary-container': '#949595',
        'outline': '#89919e',
        'on-secondary': '#3c2f00',
        'secondary': '#e9c349',
        'on-primary-fixed': '#001f24',
        'on-secondary-container': '#342800',
        'primary-container': '#00a4b7',
        'error': '#ffb4ab',
        'on-primary-fixed-variant': '#004f58',
        'primary-fixed-dim': '#00daf3',
        'on-secondary-fixed-variant': '#574500',
        'tertiary': '#c6c6c6',
        'outline-variant': '#3f4753',
        'inverse-surface': '#e4e1e9',
        'inverse-primary': '#006875',
        'on-error-container': '#ffdad6',
        'on-tertiary': '#2f3131',
        'on-tertiary-fixed-variant': '#454747',
        'on-tertiary-fixed': '#1a1c1c',
        'surface-container-low': '#1b1b20',
        'surface-container': '#1f1f25',
        'surface': '#131318',
        'primary-fixed': '#9cf0ff',
        'on-error': '#690005',
        'inverse-on-surface': '#303036',
        'error-container': '#93000a',
        'tertiary-fixed-dim': '#c6c6c6',
        'secondary-fixed': '#ffe088',
        'background': '#131318',
        'surface-tint': '#00daf3',
        'surface-bright': '#39383e',
        'on-primary-container': '#00333a',
        'secondary-fixed-dim': '#e9c349',
        'on-tertiary-container': '#2c2e2e',
        'tertiary-fixed': '#e2e2e2',
        'on-secondary-fixed': '#241a00',
        'surface-dim': '#131318',
        'surface-container-lowest': '#0e0e13',
        'on-background': '#e4e1e9',
        'secondary-container': '#af8d11',
        'surface-container-highest': '#35343a',
        'on-surface': '#e4e1e9',
        'on-surface-variant': '#bfc7d5',
        'primary': '#00daf3',
      },
      borderRadius: {
        DEFAULT: '0px',
        none: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        '3xl': '0px',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Space Grotesk', 'monospace'],
      },
    },
  },
  plugins: [],
}

export default config
