import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#1e213a',
        'on-primary': '#000000',
        'surface-container-high': '#1a1c32',
        'tertiary-container': '#334155',
        'outline': '#475569',
        'on-secondary': '#ffffff',
        'secondary': '#d946ef',
        'on-primary-fixed': '#001f24',
        'on-secondary-container': '#fdf4ff',
        'primary-container': '#005260',
        'error': '#ff4b60',
        'on-primary-fixed-variant': '#004f58',
        'primary-fixed-dim': '#00f0ff',
        'on-secondary-fixed-variant': '#86198f',
        'tertiary': '#94a3b8',
        'outline-variant': '#334155',
        'inverse-surface': '#f1f5f9',
        'inverse-primary': '#008fa3',
        'on-error-container': '#ffe4e6',
        'on-tertiary': '#0f172a',
        'on-tertiary-fixed-variant': '#334155',
        'on-tertiary-fixed': '#0f172a',
        'surface-container-low': '#0e0f1a',
        'surface-container': '#121424',
        'surface': '#0a0a12',
        'primary-fixed': '#a5f3fc',
        'on-error': '#ffffff',
        'inverse-on-surface': '#1e293b',
        'error-container': '#881337',
        'tertiary-fixed-dim': '#94a3b8',
        'secondary-fixed': '#f5d0fe',
        'background': '#0a0a12',
        'surface-tint': '#00f0ff',
        'surface-bright': '#2b2f52',
        'on-primary-container': '#e0f2fe',
        'secondary-fixed-dim': '#d946ef',
        'on-tertiary-container': '#f1f5f9',
        'tertiary-fixed': '#e2e8f0',
        'on-secondary-fixed': '#4a044e',
        'surface-dim': '#0a0a12',
        'surface-container-lowest': '#07070d',
        'on-background': '#f1f5f9',
        'secondary-container': '#701a75',
        'surface-container-highest': '#242745',
        'on-surface': '#f1f5f9',
        'on-surface-variant': '#cbd5e1',
        'primary': '#00f0ff',
      },
      borderRadius: {
        none: '0px',
        xs: '4px',
        sm: '6px',
        DEFAULT: '8px',
        md: '10px',
        lg: '14px',
        xl: '18px',
        '2xl': '24px',
        '3xl': '32px',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Manrope', 'Inter', 'sans-serif'],
        label: ['Space Grotesk', 'JetBrains Mono', 'monospace'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}

export default config
